apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: default
  labels:
    app: order-system-customers
spec:
  type: LoadBalancer
  selector:
    app: order-system-customers
  ports:
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https-port
      protocol: TCP
      port: 443
      targetPort: 3001
