apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: default
  labels:
    app: order-system-customers
spec:
  replicas: 3 # Define a quantidade de réplicas para alta disponibilidade
  selector:
    matchLabels:
      app: order-system-customers
  template:
    metadata:
      labels:
        app: order-system-customers
    spec:
      containers:
        - name: customers-api
          image: 672970943008.dkr.ecr.us-east-1.amazonaws.com/order-system/customers:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: api-configmap
            - secretRef:
                name: api-secrets
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
      restartPolicy: Always
