apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: default
  labels:
    app: order-system-customers
spec:
  type: LoadBalancer
  selector:
    app: order-system-customers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
