apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
  namespace: default
data:
  APP_PORT: "3000"
  APP_ENV: "production"
  DYNAMODB_TABLE_NAME: "customers-table" # Nome da tabela no DynamoDB
  AWS_REGION: "us-east-1" # Região onde o DynamoDB está localizado
