apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: api-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["dynamodb.services.k8s.aws"]
    resources: ["*"]  # Permissões para acessar DynamoDB
    verbs: ["*"]  # Permissões de leitura, escrita, etc.
