apiVersion: v1
kind: Service
metadata:
  name: order-system-customers
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: order-system-customers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
