apiVersion: v1
kind: Service
metadata:
  name: customers-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Use "alb" para Application Load Balancer
spec:
  type: LoadBalancer
  selector:
    app: customers-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
