version: '3'
services:
  # Serviço de DynamoDB
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=dynamodb-local
      - AWS_SECRET_ACCESS_KEY=dynamodb-local
    volumes:
      - ./dynamodb-data:/home/dynamo/db
    networks:
      - app-network

  # Serviço da aplicação
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-system-app
    ports:
      - "3000:3000"
    environment:
      - AWS_REGION=us-east-1
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
