name: Deploy to EKS

on:
  push:
    branches:
      - main  # Trigger para a branch principal, você pode alterar para sua branch de produção ou de deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checando repo
      uses: actions/checkout@v3

    - name: Configurar Credenciais AWS
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Set up kubectl for EKS
      run: |
        aws eks --region us-west-2 update-kubeconfig --name nestjs-cluster

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and push Docker image
      run: |
        docker build -t nestjs-app .
        docker tag nestjs-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/nestjs-app:latest
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/nestjs-app:latest

    - name: Update Kubernetes Deployment in EKS
      run: |
        kubectl set image deployment/nestjs-deployment nestjs-container=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/nestjs-app:latest
        kubectl rollout restart deployment/nestjs-deployment

    - name: Wait for Kubernetes deployment to be rolled out
      run: |
        kubectl rollout status deployment/nestjs-deployment
